name: Scan with kube-linter

on:
  # Note that both `push` and `pull_request` triggers should be present for GitHub to consistently present kube-linter
  # SARIF reports.
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.sha }}

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Scan files
        uses: yash-deepsource/community-analyzers-action@main
        with:
          ref: ${{ github.action_ref }}
          analyzer: "kube-linter"
          deepsource-dsn: ${{ secrets.DEEPSOURCE_DSN }}
